/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.gradle;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Main application class for the Gradle boilerplate project.
 * 
 * This class serves as the entry point for the application and demonstrates
 * basic logging and application structure.
 */
public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    /**
     * Returns a greeting message.
     * 
     * @return A greeting string
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main method - entry point of the application.
     * 
     * @param args Command line arguments
     */
    public static void main(String[] args) {
        App app = new App();
        String greeting = app.getGreeting();

        logger.info("Application started");
        logger.info("Greeting: {}", greeting);

        System.out.println(greeting);

        logger.info("Application finished");
    }
}
